project:
  type: website
  output-dir: www

website:
  navbar:
    background: light
    title: "<img src='/images/meridian-logo-black.svg' width='140'>"
    right:
      - projects.qmd
      - team.qmd
      - text: About
        href: about.qmd
      - careers.qmd
      - icon: github
        href: https://github.com/meridianlabs-ai
        aria-label: GitHub
  page-footer:
    left: "Meridian Labs is a 501(c)(3) non-profit"
    center: ""
    right: "Â© 2025 Meridian Labs"
    background: "#F8FAFC"
    foreground: "#94A3B8"
  bread-crumbs: false

format:
  html:
    theme:
      light: custom.scss
    css:
      - fonts/fonts.css
    include-in-header:
      - text: |
          <link rel="preload" href="/fonts/roboto-700.ttf" as="font" type="font/truetype" crossorigin>
          <link rel="preload" href="/fonts/roboto-400.ttf" as="font" type="font/truetype" crossorigin>
          <link rel="preload" href="/fonts/roboto-condensed-700.ttf" as="font" type="font/truetype" crossorigin>
    toc: true
    grid:
      sidebar-width: 350px
