project:
  type: website
  output-dir: www

website:
  navbar:
    background: light
    title: "<img src='/images/meridian-logo-black.svg' width='140'>"
    right:
      - projects.qmd
      - team.qmd
      - text: About
        href: about.qmd
      - careers.qmd
      - icon: twitter
        href: https://x.com/meridianlabs_ai
        aria-label: Twitter
      - icon: linkedin
        href: https://www.linkedin.com/company/meridian-research-labs/
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/meridianlabs-ai
        aria-label: GitHub
  page-footer:
    left: |
      <span class="contact-org">Meridian Labs</span> Â· <span>A 501(c)(3) nonprofit</span><br>501 Boylston St, 10th Floor, Boston, MA 02116
    right: |
      <a href="mailto:info@meridianlabs.ai">info@meridianlabs.ai</a>
    background: "#F8FAFC"
  bread-crumbs: false

format:
  html:
    theme:
      light: custom.scss
    css:
      - fonts/fonts.css
    include-in-header:
      - text: |
          <link rel="preload" href="/fonts/roboto-700.ttf" as="font" type="font/truetype" crossorigin>
          <link rel="preload" href="/fonts/roboto-400.ttf" as="font" type="font/truetype" crossorigin>
          <link rel="preload" href="/fonts/roboto-condensed-700.ttf" as="font" type="font/truetype" crossorigin>
    toc: true
    grid:
      sidebar-width: 350px
