project:
  type: website
  output-dir: www

website:
  navbar:
    background: "#3399F322"
    title: "<img src='/images/meridian-logo-black.svg' width='120'>"
    left:
      - mission.qmd
      - team.qmd
      - careers.qmd
      - href: contact.qmd
        text: Contact
  page-footer: 
    left: ""
    center: "Meridian Labs is a 501(c)(3) non-profit<br/>Â© 2025 Meridian Labs"
    right: ""
  bread-crumbs: true

format:
  html:
    theme:
      light: spacelab
    css: 
      - styles.css
      - fonts/fonts.css
    toc: true
    grid:
      sidebar-width: 350px    



